#!/usr/bin/env bash
#
# Microsoft Entra ID - Bulk User Creation
# description:
#   reads user information from a CSV file and creates
#   multiple Microsoft Entra ID users using Azure CLI.
#   temporary passwords are generated by this script (not read from
#   the CSV), so no plaintext password ever needs to be stored at rest.
#
# CSV format (with header row): DisplayName,UserPrincipalName

set -euo pipefail

CSV_FILE="${1:-users.csv}"
TIMESTAMP="$(date +%Y%m%d_%H%M%S)"
LOG_FILE="entra_user_provisioning_${TIMESTAMP}.log"
CREDS_FILE="entra_new_user_credentials_${TIMESTAMP}.csv"

CREATED_USERS=()
FAILED_USERS=()
SKIPPED_USERS=()

log() {
    echo "$1" | tee -a "$LOG_FILE"
}

# generates a random pass
generate_password() {
    local upper lower digit symbol rest all
    upper=$(tr -dc 'A-Z' </dev/urandom | head -c1)
    lower=$(tr -dc 'a-z' </dev/urandom | head -c1)
    digit=$(tr -dc '0-9' </dev/urandom | head -c1)
    symbol=$(tr -dc '!@#$%^&*_+-=' </dev/urandom | head -c1)
    all='A-Za-z0-9!@#$%^&*_+-='
    rest=$(tr -dc "$all" </dev/urandom | head -c12)
    # shuffle the combined characters so required-class chars aren't
    # always in the same spots
    echo "${upper}${lower}${digit}${symbol}${rest}" | fold -w1 | shuf | tr -d '\n'
}

# basic checks
if ! command -v az &>/dev/null; then
    echo "ERROR: Azure CLI is not installed." >&2
    exit 1
fi

if ! az account show &>/dev/null; then
    echo "ERROR: You are not logged into Azure." >&2
    echo "Run: az login" >&2
    exit 1
fi
log "Azure authentication confirmed."
log ""

if [[ ! -f "$CSV_FILE" ]]; then
    echo "ERROR: CSV file '$CSV_FILE' was not found." >&2
    exit 1
fi

log "========================================"
log " Microsoft Entra ID User Provisioning"
log "========================================"
log ""

# credentials file will hold the ONLY copy of the generated temp
# passwords. !!! lock it down before writing anything sensitive to it
umask 077
echo "DisplayName,UserPrincipalName,TemporaryPassword" > "$CREDS_FILE"
chmod 600 "$CREDS_FILE"

mapfile -t CSV_LINES < <(tail -n +2 "$CSV_FILE")
for line in "${CSV_LINES[@]}"; do
    # strip a trailing \r in case the CSV has Windows line endings,
    # and skip fully blank lines
    line="${line%$'\r'}"
    [[ -z "${line//[[:space:]]/}" ]] && continue

    IFS=',' read -r DISPLAY_NAME USERNAME <<< "$line"

    # trim stray whitespace around fields.
    DISPLAY_NAME="$(echo -n "$DISPLAY_NAME" | xargs)"
    USERNAME="$(echo -n "$USERNAME" | xargs)"

    if [[ -z "$DISPLAY_NAME" || -z "$USERNAME" ]]; then
        log "WARNING: Skipping malformed row: '$line'"
        SKIPPED_USERS+=("$line")
        continue
    fi

    log "Creating user: $DISPLAY_NAME"
    log "UPN: $USERNAME"

    if az ad user show --id "$USERNAME" &>/dev/null; then
        log "WARNING: User already exists: $USERNAME"
        SKIPPED_USERS+=("$USERNAME")
        log ""
        continue
    fi

    PASSWORD="$(generate_password)"

    if az ad user create \
        --display-name "$DISPLAY_NAME" \
        --user-principal-name "$USERNAME" \
        --password "$PASSWORD" \
        --force-change-password-next-sign-in true \
        >>"$LOG_FILE" 2>&1
    then
        log "SUCCESS: Created $DISPLAY_NAME"
        echo "${DISPLAY_NAME},${USERNAME},${PASSWORD}" >> "$CREDS_FILE"
        CREATED_USERS+=("$USERNAME")
    else
        log "ERROR: Failed to create $DISPLAY_NAME (see $LOG_FILE for details)"
        FAILED_USERS+=("$USERNAME")
    fi
    # password no longer needed in memory once written/logged
    unset PASSWORD
    log ""
done

log "========================================"
log " Provisioning Summary"
log "========================================"
log ""
log "Successfully created (${#CREATED_USERS[@]}):"
for USER in "${CREATED_USERS[@]:-}"; do
    [[ -n "$USER" ]] && log "  ✓ $USER"
done
log ""
log "Skipped / already existed (${#SKIPPED_USERS[@]}):"
for USER in "${SKIPPED_USERS[@]:-}"; do
    [[ -n "$USER" ]] && log "  - $USER"
done
log ""
log "Failed (${#FAILED_USERS[@]}):"
for USER in "${FAILED_USERS[@]:-}"; do
    [[ -n "$USER" ]] && log "  ✗ $USER"
done
log ""

if [[ ${#CREATED_USERS[@]} -gt 0 ]]; then
    log "Temporary passwords for newly created users were written to:"
    log "  $CREDS_FILE (permissions 600 — share it with each user over a"
    log "  secure channel, then delete it once they've signed in)."
else
    rm -f "$CREDS_FILE"
fi
log ""

# securely remove the input CSV now that it's been processed
if command -v shred &>/dev/null; then
    shred -u "$CSV_FILE"
    log "Input CSV '$CSV_FILE' securely deleted (shred)."
else
    rm -f "$CSV_FILE"
    log "WARNING: 'shred' not available; '$CSV_FILE' was removed with rm"
    log "         (not securely wiped). Install 'shred' (coreutils) for"
    log "         secure deletion in the future."
fi

log ""
log "Provisioning completed. Full log written to: $LOG_FILE"
