<#
.SYNOPSIS
    Microsoft Entra ID - Bulk User Creation (Windows / PowerShell)

.DESCRIPTION
    reads DisplayName,UserPrincipalName pairs from a CSV file and creates
    Microsoft Entra ID users using the Microsoft Graph PowerShell SDK.
    temporary passwords are generated by this script (never read from
    the CSV), written to a separate, tightly-permissioned credentials
    file, and the source CSV is wiped once processing completes.

.PARAMETER CsvFile
    Path to the input CSV. Must have a header row:
    DisplayName,UserPrincipalName

.EXAMPLE
    .\Create-EntraUsers.ps1 -CsvFile .\users.csv

.NOTES
    Requires the Microsoft.Graph PowerShell SDK:
      Install-Module Microsoft.Graph -Scope CurrentUser
    Requires an account with User Administrator (or equivalent) rights
    and the Graph delegated scope User.ReadWrite.All.
#>

[CmdletBinding()]
param(
    [Parameter(Position = 0)]
    [string]$CsvFile = "users.csv"
)
 
$ErrorActionPreference = "Stop"
 
$Timestamp   = Get-Date -Format "yyyyMMdd_HHmmss"
$LogFile     = "entra_user_provisioning_$Timestamp.log"
$CredsFile   = "entra_new_user_credentials_$Timestamp.csv"
 
$CreatedUsers = [System.Collections.Generic.List[string]]::new()
$FailedUsers  = [System.Collections.Generic.List[string]]::new()
$SkippedUsers = [System.Collections.Generic.List[string]]::new()
 
function Write-Log {
    param([string]$Message)
    Write-Host $Message
    Add-Content -Path $LogFile -Value $Message
}
 
function New-RandomPassword {
    # builds a 16-char password guaranteed to contain an uppercase letter,
    # a lowercase letter, a digit, and a symbol (Entra's default
    # complexity policy), then shuffles the characters
    $upper   = -join ((65..90)  | Get-Random -Count 1 | ForEach-Object { [char]$_ })
    $lower   = -join ((97..122) | Get-Random -Count 1 | ForEach-Object { [char]$_ })
    $digit   = -join ((48..57)  | Get-Random -Count 1 | ForEach-Object { [char]$_ })
    $symbols = '!@#$%^&*_+-='.ToCharArray()
    $symbol  = -join ($symbols | Get-Random -Count 1)
 
    $allChars = (48..57 + 65..90 + 97..122) | ForEach-Object { [char]$_ }
    $allChars += $symbols
    $rest = -join (1..12 | ForEach-Object { $allChars | Get-Random })
 
    $combined = ($upper + $lower + $digit + $symbol + $rest).ToCharArray()
    # Fisher-Yates style shuffle via Get-Random
    -join ($combined | Sort-Object { Get-Random })
}
 
# basic checks
if (-not (Get-Module -ListAvailable -Name Microsoft.Graph.Users)) {
    Write-Error "ERROR: Microsoft.Graph PowerShell module is not installed.`nRun: Install-Module Microsoft.Graph -Scope CurrentUser"
    exit 1
}
 
Import-Module Microsoft.Graph.Users -ErrorAction Stop
Import-Module Microsoft.Graph.Authentication -ErrorAction Stop
 
try {
    $context = Get-MgContext
    if (-not $context) {
        throw "Not connected"
    }
}
catch {
    Write-Host "Not connected to Microsoft Graph. Launching sign-in..."
    Connect-MgGraph -Scopes "User.ReadWrite.All" | Out-Null
}
 
Write-Log "Microsoft Graph authentication confirmed."
Write-Log ""
 
if (-not (Test-Path -Path $CsvFile -PathType Leaf)) {
    Write-Error "ERROR: CSV file '$CsvFile' was not found."
    exit 1
}
 
Write-Log "========================================"
Write-Log " Microsoft Entra ID User Provisioning"
Write-Log "========================================"
Write-Log ""
 
# credentials file holds the ONLY copy of the generated temp passwords
"DisplayName,UserPrincipalName,TemporaryPassword" | Out-File -FilePath $CredsFile -Encoding UTF8
 
$rows = Import-Csv -Path $CsvFile
 
foreach ($row in $rows) {
    # guard against missing/null properties BEFORE calling .Trim() on them,
    # a row with a missing trailing field gives a $null property, and
    # $null.Trim() throws a terminating error that isn't caught by
    # $ErrorActionPreference, killing the whole run partway through
    $displayNameRaw = $row.DisplayName
    $usernameRaw    = $row.UserPrincipalName
 
    if ([string]::IsNullOrWhiteSpace($displayNameRaw) -or [string]::IsNullOrWhiteSpace($usernameRaw)) {
        Write-Log "WARNING: Skipping malformed row: '$($row | Out-String)'"
        $SkippedUsers.Add("(malformed row)")
        continue
    }
 
    $displayName = $displayNameRaw.Trim()
    $username    = $usernameRaw.Trim()
 
    Write-Log "Creating user: $displayName"
    Write-Log "UPN: $username"
 
    $existing = $null
    $lookupFailed = $false
    try {
        $existing = Get-MgUser -UserId $username -ErrorAction Stop
    }
    catch {
        # only a genuine "not found" means it's safe to proceed with creation.
        # any other error (throttling, permissions, network) should NOT be
        # silently treated as "doesn't exist" !! skip and flag it instead.
        if ($_.Exception.Message -match "does not exist|not found|404") {
            $existing = $null
        }
        else {
            Write-Log "ERROR: Could not verify whether $username exists -- $($_.Exception.Message)"
            $FailedUsers.Add($username)
            $lookupFailed = $true
        }
    }
 
    if ($lookupFailed) {
        Write-Log ""
        continue
    }
 
    if ($existing) {
        Write-Log "WARNING: User already exists: $username"
        $SkippedUsers.Add($username)
        Write-Log ""
        continue
    }
 
    $password = New-RandomPassword
 
    $passwordProfile = @{
        Password                             = $password
        ForceChangePasswordNextSignIn        = $true
    }
 
    # UPN's left-of-@ portion, sanitized, makes a reasonable MailNickname.
    $mailNickname = ($username -split "@")[0] -replace '[^a-zA-Z0-9]', ''
 
    try {
        New-MgUser -DisplayName $displayName `
            -UserPrincipalName $username `
            -MailNickname $mailNickname `
            -AccountEnabled `
            -PasswordProfile $passwordProfile `
            -ErrorAction Stop | Out-Null
 
        Write-Log "SUCCESS: Created $displayName"
        Add-Content -Path $CredsFile -Value "$displayName,$username,$password"
        $CreatedUsers.Add($username)
    }
    catch {
        Write-Log "ERROR: Failed to create $displayName -- $($_.Exception.Message)"
        $FailedUsers.Add($username)
    }
 
    $password = $null
    Write-Log ""
}
 
Write-Log "========================================"
Write-Log " Provisioning Summary"
Write-Log "========================================"
Write-Log ""
Write-Log "Successfully created ($($CreatedUsers.Count)):"
foreach ($u in $CreatedUsers) { Write-Log "  [OK] $u" }
Write-Log ""
Write-Log "Skipped / already existed ($($SkippedUsers.Count)):"
foreach ($u in $SkippedUsers) { Write-Log "  [--] $u" }
Write-Log ""
Write-Log "Failed ($($FailedUsers.Count)):"
foreach ($u in $FailedUsers) { Write-Log "  [X] $u" }
Write-Log ""
 
if ($CreatedUsers.Count -gt 0) {
    # restrict the credentials file to the current user only. Wrapped in
    # try/catch so a failure here (non-NTFS volume, restricted perms, etc.)
    # can't abort the script before the summary/cleanup below runs --
    # users have already been created in Entra at this point regardless
    try {
        $acl = Get-Acl $CredsFile
        $acl.SetAccessRuleProtection($true, $false)
        $rule = New-Object System.Security.AccessControl.FileSystemAccessRule(
            [System.Security.Principal.WindowsIdentity]::GetCurrent().Name,
            "FullControl", "Allow"
        )
        $acl.AddAccessRule($rule)
        Set-Acl -Path $CredsFile -AclObject $acl
        Write-Log "Temporary passwords for newly created users were written to:"
        Write-Log "  $CredsFile (access restricted to your account -- share each"
        Write-Log "  password with its user over a secure channel, then delete"
        Write-Log "  the file once they've signed in)."
    }
    catch {
        Write-Log "WARNING: Could not restrict permissions on $CredsFile -- $($_.Exception.Message)"
        Write-Log "  The file still contains plaintext temporary passwords. Secure or delete it manually."
    }
}
else {
    Remove-Item -Path $CredsFile -Force -ErrorAction SilentlyContinue
}
Write-Log ""
 
# remove the input CSV now that it's been processed
# PowerShell/NTFS has no built-in secure-wipe equivalent to `shred`;
# Remove-Item only unlinks the file. wrapped in try/catch so
# a locked/read-only file doesn't prevent the final summary from printing.
try {
    Remove-Item -Path $CsvFile -Force -ErrorAction Stop
    Write-Log "Input CSV '$CsvFile' deleted."
}
catch {
    Write-Log "WARNING: Could not delete input CSV '$CsvFile' -- $($_.Exception.Message)"
}
Write-Log ""
Write-Log "Provisioning completed. Full log written to: $LogFile"
